services:
  - type: web
    name: horal
    env: python
    plan: free  # or 'starter' or other paid plan
    buildCommand: >
      pip install -r requirements.txt &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      python seed.py
    startCommand: gunicorn gathrify_backend.wsgi:application